version: '3.8'
  
services:
  mysqldb: 
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB__PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  app:
    build: .
    depends_on:
      - mysqldb
      - redis
    links:
      - mysqldb
      - redis
    ports:
      - 3000:3000
